#Untested
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scala-template-deployment
  annotations:
    iam.amazonaws.com/role: kube_template_role
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: scala-template
    spec:
      containers:
      - name: scala-template
        image: 077077460384.dkr.ecr.ap-southeast-2.amazonaws.com/scala-template:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: scala-template
  labels:
    app: scala-template
    tier: web
spec:
  type: NodePort
  selector:
    app: scala-template
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: scala-template
spec:
  rules:
  - host: scala-template.dev.k8sinternal.com
    http:
      paths:
      - path: /
        backend:
          serviceName: scala-template
          servicePort: 80
